name: "Release"
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  build-linux-x86_64-extension:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: make loadable
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-linux-x86_64-extension
          path: dist/*
  build-linux-x86_64-python:
    runs-on: ubuntu-20.04
    needs: [build-linux-x86_64-extension]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: sqlite-tg-linux-x86_64-extension
          path: dist/
      - uses: actions/setup-python@v3
      - run: pip install wheel build
      - run: make python
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-linux-x86_64-wheels
          path: dist/wheels/*.whl
  build-macos-x86_64-extension:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: make loadable
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-macos-x86_64-extension
          path: dist/*
  build-macos-x86_64-python:
    runs-on: macos-11
    needs: [build-macos-x86_64-extension]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: sqlite-tg-macos-x86_64-extension
          path: dist/
      - uses: actions/setup-python@v3
      - run: pip install wheel build
      - run: make python
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-macos-x86_64-wheels
          path: dist/wheels/*.whl
  build-macos-aarch64-extension:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: make loadable CFLAGS="-target arm64-apple-macos11"
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-macos-aarch64-extension
          path: dist/*
  build-macos-aarch64-python:
    runs-on: macos-latest
    needs: [build-macos-aarch64-extension]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: sqlite-tg-macos-aarch64-extension
          path: dist/
      - uses: actions/setup-python@v3
      - run: pip install wheel build
      - run: make python IS_MACOS_ARM=1
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-macos-aarch64-wheels
          path: dist/wheels/*.whl
  build-windows-x86_64-extension:
    runs-on: windows-2019
    if: false
    steps:
      - uses: actions/checkout@v3
      - run: make loadable
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-windows-x86_64-extension
          path: dist/*
  build-windows-x86_64-python:
    runs-on: windows-2019
    needs: [build-windows-x86_64-extension]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: sqlite-tg-windows-x86_64-extension
          path: dist/
      - uses: actions/setup-python@v3
      - run: pip install wheel build
      - run: make python
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-windows-x86_64-wheels
          path: dist/wheels/*.whl
  build-datasette-sqlite-utils:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install wheel build
      - run: make datasette sqlite-utils
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-datasette-sqlite-utils-wheels
          path: dist/wheels/*.whl
  upload-deno:
    needs: [
        build-linux-x86_64-extension,
        build-macos-x86_64-extension,
        build-macos-aarch64-extension,
        #build-windows-x86_64-extension,
      ]
    outputs:
      deno-checksums: ${{ steps.deno-assets.outputs.result }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
      - id: deno-assets
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const script = require('.github/workflows/upload-deno-assets.js')
            return await script({github, context})
  upload-extensions:
    needs: [
        build-linux-x86_64-extension,
        build-macos-x86_64-extension,
        build-macos-aarch64-extension,
        #build-windows-x86_64-extension,
      ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      checksums: ${{ steps.upload-spm.outputs.asset-checksums }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
      - uses: asg017/upload-spm@main
        id: upload-spm
        with:
          name: sqlite-tg
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: |
            macos-x86_64:   sqlite-tg-macos-x86_64-extension/*
            macos-aarch64:  sqlite-tg-macos-aarch64-extension/*
            linux-x86_64:   sqlite-tg-linux-x86_64-extension/*
          #windows-x86_64: sqlite-tg-windows-x86_64-extension/*
  upload-checksums:
    needs: [upload-extensions, upload-deno]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      checksums: ${{ steps.upload-checksums.outputs.result }}
    steps:
      - id: upload-checksums
        uses: actions/github-script@v6
        env:
          CHECKSUMS: "${{ needs.upload-extensions.outputs.checksums }}\n${{ needs.upload-deno.outputs.deno-checksums }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { owner, repo } = context.repo;
            const release = await github.rest.repos.getReleaseByTag({
              owner,
              repo,
              tag: process.env.GITHUB_REF.replace("refs/tags/", ""),
            });
            const release_id = release.data.id;
            github.rest.repos.uploadReleaseAsset({
              owner,
              repo,
              release_id,
              name: "checksums.txt",
              data: process.env.CHECKSUMS,
            });
            return process.env.CHECKSUMS
  upload-gem:
    needs: [
        build-linux-x86_64-extension,
        build-macos-x86_64-extension,
        build-macos-aarch64-extension,
        #build-windows-x86_64-extension,
      ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: |
          rm bindings/ruby/lib/*.{dylib,so,dll} || true
          cp sqlite-tg-macos-x86_64-extension/*.dylib bindings/ruby/lib
          gem -C bindings/ruby build -o x86_64-darwin.gem sqlite_tg.gemspec
        env:
          PLATFORM: x86_64-darwin
      - run: |
          rm bindings/ruby/lib/*.{dylib,so,dll} || true
          cp sqlite-tg-macos-aarch64-extension/*.dylib bindings/ruby/lib
          gem -C bindings/ruby build -o arm64-darwin.gem sqlite_tg.gemspec
        env:
          PLATFORM: arm64-darwin
      - run: |
          rm bindings/ruby/lib/*.{dylib,so,dll} || true
          cp sqlite-tg-linux-x86_64-extension/*.so bindings/ruby/lib
          gem -C bindings/ruby build -o x86_64-linux.gem sqlite_tg.gemspec
        env:
          PLATFORM: x86_64-linux
      - run: |
          rm bindings/ruby/lib/*.{dylib,so,dll} || true
          cp sqlite-tg-windows-x86_64-extension/*.dll bindings/ruby/lib
          gem -C bindings/ruby build -o x64-mingw32.gem sqlite_tg.gemspec
        if: false
        env:
          PLATFORM: x64-mingw32
      - run: |
          gem push bindings/ruby/x86_64-darwin.gem
          gem push bindings/ruby/arm64-darwin.gem
          gem push bindings/ruby/x86_64-linux.gem
        #gem push bindings/ruby/x64-mingw32.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
  upload-npm:
    needs: [
        build-linux-x86_64-extension,
        build-macos-x86_64-extension,
        build-macos-aarch64-extension,
        #build-windows-x86_64-extension,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
      - run: |
          cp sqlite-tg-linux-x86_64-extension/*.so bindings/node/sqlite-tg-linux-x64/lib/
          cp sqlite-tg-macos-x86_64-extension/*.dylib bindings/node/sqlite-tg-darwin-x64/lib/
          cp sqlite-tg-macos-aarch64-extension/*.dylib bindings/node/sqlite-tg-darwin-arm64/lib/
        #cp sqlite-tg-windows-x86_64-extension/*.dll bindings/node/sqlite-tg-windows-x64/lib/
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Publish NPM sqlite-tg-linux-x64
        working-directory: bindings/node/sqlite-tg-linux-x64
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish NPM sqlite-tg-darwin-x64
        working-directory: bindings/node/sqlite-tg-darwin-x64
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish NPM sqlite-tg-darwin-arm64
        working-directory: bindings/node/sqlite-tg-darwin-arm64
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #- name: Publish NPM sqlite-tg-windows-x64
      #  working-directory: bindings/node/sqlite-tg-windows-x64
      #  run: npm publish --access public
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish NPM sqlite-tg
        working-directory: bindings/node/sqlite-tg
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  upload-pypi:
    needs: [
        build-linux-x86_64-python,
        build-macos-x86_64-python,
        build-macos-aarch64-python,
        #build-windows-x86_64-python,
        build-datasette-sqlite-utils,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sqlite-tg-linux-x86_64-wheels
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: sqlite-tg-macos-x86_64-wheels
          path: dist
      - uses: actions/download-artifact@v3
        with:
          name: sqlite-tg-macos-aarch64-wheels
          path: dist
      #- uses: actions/download-artifact@v3
      #  with:
      #    name: sqlite-tg-windows-x86_64-wheels
      #    path: dist
      - uses: actions/download-artifact@v3
        with:
          name: sqlite-tg-datasette-sqlite-utils-wheels
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
