name: Deploy Site
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: bindings/wasm/package-lock.json
      - run: npm ci
        working-directory: bindings/wasm
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: "latest"
      - run: make -f wasm.mk all
      - run: make wasm-playground
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist/wasm-playground
      - id: deployment
        uses: actions/deploy-pages@v1
