name: "build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-linux-x86_64-extension:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: make loadable
      - run: pip install pytest syrupy shapely; make test-loadable
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-linux-x86_64-extension
          path: dist/*
  build-macos-x86_64-extension:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: make loadable
      - run: /usr/local/opt/python@3/libexec/bin/python -m pip install pytest syrupy shapely --break-system-packages; make test-loadable python=/usr/local/opt/python@3/libexec/bin/python
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-macos-x86_64-extension
          path: dist/*
  build-macos-aarch64-extension:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - run: make loadable
      - run: /opt/homebrew/opt/python3/libexec/bin/python -m pip install pytest syrupy shapely --break-system-packages; make test-loadable python=/opt/homebrew/opt/python3/libexec/bin/python
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-macos-aarch64-extension
          path: dist/*
  build-windows-x86_64-extension:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: make loadable
      - run: pip install pytest syrupy shapely; make test-loadable
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-windows-x86_64-extension
          path: dist/*
  build-wasm32-emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: "latest"
      - run: make sqlite-tg.h
      - run: make wasm
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-tg-wasm32-emscripten
          path: dist/*
