name: "build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: linux-x86_64
          - os: ubuntu-22.04-arm
            target: linux-aarch64
          - os: macos-13
            target: macos-x86_64
          - os: macos-14
            target: macos-aarch64
          - os: windows-latest
            target: windows-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: make loadable
      - run: make test-loadable
      - name: install solite
        if: runner.os != 'Windows'
        run: |
          uv tool install solite
          echo "$(uv tool dir --bin)" >> "$GITHUB_PATH"
      - run: make test-api
        if: runner.os != 'Windows'
      - run: make docs-check
        if: runner.os != 'Windows'
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-tg-${{ matrix.target }}-extension
          path: dist/*
  build-wasm32-emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: "latest"
      - run: make sqlite-tg.h
      - run: make wasm
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-tg-wasm32-emscripten
          path: dist/*
          include-hidden-files: true
  test-windows-rust:
    strategy:
      matrix:
        include:
          #- os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          default: true
      - run: make sqlite-tg.h
      - run: make deps
        working-directory: ./bindings/rust
      - run: cargo test
        env:
            CARGO_BUILD_TARGET: x86_64-pc-windows-gnu
        working-directory: ./bindings/rust
