name: "build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-linux-x86_64-extension:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: make loadable
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-linux-x86_64-extension
          path: dist/*
  build-macos-x86_64-extension:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: make loadable
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-macos-x86_64-extension
          path: dist/*
  build-macos-aarch64-extension:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: make loadable static CFLAGS="-target arm64-apple-macos11"
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-macos-aarch64-extension
          path: dist/*
  build-windows-x86_64-extension:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - run: make loadable static
      - uses: actions/upload-artifact@v3
        with:
          name: sqlite-tg-windows-x86_64-extension
          path: dist/*
